### ISSUE TITLE
leave package-lock within project's repository

### ISSUE THREAD

**Issue by alexcrack** [NatalliaSh/Sushi-project#4]
https://github.com/NatalliaSh/Sushi-project/blob/3969c14f3dbf37d1ae9fe7a5fb076758664fcb87/.gitignore#L4C1-L4C18

Better to leave package-lock within project's repository.
When project builds using CI the package-lock file will be used to clearly install modules with command:
```
npm ci
```
And will prevent modules versions mismatch

**Comment by NatalliaSh** [comment]
Done. Thanks
